#!/bin/bash
# Skrip Update Total untuk Yoga Pro 7 (OS + SBo)

echo "--- 1. Update Mirror Slackpkg ---"
slackpkg update

echo "--- 2. Upgrade OS (Official Packages) ---"
slackpkg upgrade-all

echo "--- 3. Update Sync sbopkg (SBo Repo) ---"
sbopkg -r

echo "--- 4. Cek Update untuk Aplikasi SBo ---"
sqg -a
sbopkg -u

echo "--- SEMUA BERES! ---"
